# Generated by Django 3.2.3 on 2023-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriketPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=34)),
                ('age', models.PositiveIntegerField(max_length=90)),
                ('handed', models.CharField(max_length=8)),
                ('bowlingtype', models.CharField(max_length=10)),
                ('battingVspin', models.PositiveIntegerField(max_length=30)),
                ('battingVpace', models.PositiveIntegerField(max_length=30)),
                ('bowling', models.PositiveIntegerField(max_length=30)),
                ('experience', models.PositiveIntegerField(max_length=30)),
                ('fielding', models.PositiveIntegerField(max_length=30)),
                ('region', models.CharField(max_length=34)),
            ],
        ),
    ]
