# Generated by Django 3.2.3 on 2023-03-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_calls', '0002_auto_20230208_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricketteam',
            old_name='teamIamge',
            new_name='teamImage',
        ),
        migrations.AddField(
            model_name='cricketteam',
            name='userRegion',
            field=models.CharField(default='testzone', max_length=50),
            preserve_default=False,
        ),
    ]
