# Generated by Django 4.1.5 on 2023-04-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_calls', '0003_alter_cricketteam_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricketteam',
            old_name='userRegion',
            new_name='country',
        ),
    ]
