# Generated by Django 4.1.5 on 2023-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_calls', '0005_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='id',
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_id',
            field=models.AutoField(default='4', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenged_team_id',
            field=models.PositiveIntegerField(default=5, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
