# Generated by Django 4.1.5 on 2023-05-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_calls', '0008_alter_challenges_date_and_time_playereleven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenged_team_name',
            field=models.CharField(default='t', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenger_team_name',
            field=models.CharField(default='r', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='user_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
