# Generated by Django 4.1.5 on 2023-05-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_calls', '0009_challenges_challenged_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenges',
            name='user_name',
            field=models.CharField(max_length=23),
        ),
    ]
